"""
Toon format generator for Semcod ecosystem integration.
"""

from datetime import datetime
from typing import Optional
from pathlib import Path

from deta.builder.topology import InfraTopology


def generate_toon(topology: InfraTopology, project_name: Optional[str] = None) -> str:
    """
    Generate toon format output for infrastructure status.
    
    Args:
        topology: InfraTopology object
        project_name: Optional project name (defaults to 'project')
        
    Returns:
        Toon-formatted string
    """
    project = project_name or "project"
    services = list(topology.services.values())
    endpoints = topology.endpoints
    anomalies = topology.detect_anomalies()
    
    # Count health status
    healthy_count = sum(1 for s in services if s.healthcheck)
    down_count = len(services) - healthy_count
    
    # Group anomalies by severity
    critical = [a for a in anomalies if a["severity"] == "critical"]
    errors = [a for a in anomalies if a["severity"] == "error"]
    warnings = [a for a in anomalies if a["severity"] == "warning"]
    
    lines = []
    lines.append(f"# infra.toon.yaml — generated by deta")
    lines.append(f"# {project} | {len(services)} services | {datetime.now().strftime('%Y-%m-%d')}")
    lines.append("")
    
    # Health section
    lines.append("HEALTH:")
    lines.append(f"  services: {len(services)}")
    lines.append(f"  healthy: {healthy_count}")
    lines.append(f"  down: {down_count}")
    lines.append(f"  anomalies: {len(anomalies)}")
    lines.append("")
    
    # Alerts section
    all_alerts = critical + errors + warnings
    if all_alerts:
        lines.append(f"ALERTS[{len(all_alerts)}]:")
        for alert in all_alerts:
            severity_prefix = {
                "critical": "!!!",
                "error": "!!",
                "warning": "!",
            }.get(alert["severity"], "?")
            
            alert_line = f"  {severity_prefix} {alert['type']}"
            if "service" in alert:
                alert_line += f"  {alert['service']} ({Path(alert.get('file', '')).name})"
            elif "services" in alert:
                alert_line += f"  {' → '.join(alert['services'])}"
            if "port" in alert:
                alert_line += f"  {alert['port']} → {' + '.join(alert['services'])}"
            if "env_key" in alert:
                alert_line += f"  {alert['env_key']} in {alert.get('service', '')} env"
            
            lines.append(alert_line)
        lines.append("")
    
    # Services section
    lines.append(f"SERVICES[{len(services)}]:")
    for svc in services:
        ports_str = ":".join(svc.ports) if svc.ports else "—"
        health_str = "healthcheck=✓" if svc.healthcheck else "healthcheck=✗"
        deps_str = f"deps=[{','.join(svc.depends_on)}]" if svc.depends_on else "deps=[]"
        
        lines.append(f"  {svc.name:<12} :{ports_str:<15} {health_str:<15} {deps_str}")
    lines.append("")
    
    # Endpoints section
    if endpoints:
        lines.append(f"ENDPOINTS[{len(endpoints)}]:")
        # Group endpoints by service
        by_service = {}
        for ep in endpoints:
            if ep.service_hint not in by_service:
                by_service[ep.service_hint] = []
            by_service[ep.service_hint].append(ep)
        
        for service, eps in by_service.items():
            for ep in eps[:5]:  # Limit to 5 per service
                methods_str = " ".join(ep.methods)
                lines.append(f"  {ep.path:<20} {methods_str:<6} {service} ({Path(ep.source_file).name})")
            if len(eps) > 5:
                lines.append(f"  ... and {len(eps) - 5} more endpoints for {service}")
        lines.append("")
    
    # Cycles section
    cycles = topology.detect_cycles()
    if cycles:
        lines.append(f"CYCLES[{len(cycles)}]:")
        for cycle in cycles:
            lines.append(f"  {' → '.join(cycle)}")
        lines.append("")
    
    # Hubs section
    hubs = topology.find_hubs()
    if hubs:
        lines.append(f"HUBS[{len(hubs)}]:")
        for hub in hubs:
            lines.append(f"  {hub}")
        lines.append("")
    
    return "\n".join(lines)


def save_toon(topology: InfraTopology, output_path: Path, project_name: Optional[str] = None):
    """
    Save toon format to file.
    
    Args:
        topology: InfraTopology object
        output_path: Path to save the toon file
        project_name: Optional project name
    """
    toon_content = generate_toon(topology, project_name)
    output_path.write_text(toon_content)
