"""
Toon format generator for Semcod ecosystem integration.
"""

from datetime import datetime
from typing import Optional
from pathlib import Path

from deta.builder.topology import InfraTopology
from deta.scanner.compose import ServiceDef
from deta.scanner.openapi import EndpointDef


def _format_header(project: str, service_count: int) -> list[str]:
    """Generate header section."""
    return [
        "# infra.toon.yaml — generated by deta",
        f"# {project} | {service_count} services | {datetime.now().strftime('%Y-%m-%d')}",
        "",
    ]


def _format_health(services: list[ServiceDef], anomalies: list[dict]) -> list[str]:
    """Generate HEALTH section."""
    healthy_count = sum(1 for s in services if s.healthcheck)
    down_count = len(services) - healthy_count
    return [
        "HEALTH:",
        f"  services: {len(services)}",
        f"  healthy: {healthy_count}",
        f"  down: {down_count}",
        f"  anomalies: {len(anomalies)}",
        "",
    ]


def _format_alert_line(alert: dict) -> str:
    """Format single alert line."""
    severity_prefix = {
        "critical": "!!!",
        "error": "!!",
        "warning": "!",
    }.get(alert["severity"], "?")
    
    alert_line = f"  {severity_prefix} {alert['type']}"
    if "service" in alert:
        alert_line += f"  {alert['service']} ({Path(alert.get('file', '')).name})"
    elif "services" in alert:
        alert_line += f"  {' → '.join(alert['services'])}"
    if "port" in alert:
        alert_line += f"  {alert['port']} → {' + '.join(alert['services'])}"
    if "env_key" in alert:
        alert_line += f"  {alert['env_key']} in {alert.get('service', '')} env"
    return alert_line


def _format_alerts(anomalies: list[dict]) -> list[str]:
    """Generate ALERTS section."""
    if not anomalies:
        return []
    
    # Sort by severity
    severity_order = {"critical": 0, "error": 1, "warning": 2}
    sorted_alerts = sorted(
        anomalies,
        key=lambda a: severity_order.get(a["severity"], 3)
    )
    
    lines = [f"ALERTS[{len(sorted_alerts)}]:"]
    lines.extend(_format_alert_line(a) for a in sorted_alerts)
    lines.append("")
    return lines


def _format_service_line(svc: ServiceDef) -> str:
    """Format single service line."""
    ports_str = ":".join(svc.ports) if svc.ports else "—"
    health_str = "healthcheck=✓" if svc.healthcheck else "healthcheck=✗"
    deps_str = f"deps=[{','.join(svc.depends_on)}]" if svc.depends_on else "deps=[]"
    return f"  {svc.name:<12} :{ports_str:<15} {health_str:<15} {deps_str}"


def _format_services(services: list[ServiceDef]) -> list[str]:
    """Generate SERVICES section."""
    lines = [f"SERVICES[{len(services)}]:"]
    lines.extend(_format_service_line(svc) for svc in services)
    lines.append("")
    return lines


def _group_endpoints_by_service(endpoints: list[EndpointDef]) -> dict[str, list[EndpointDef]]:
    """Group endpoints by service hint."""
    by_service: dict[str, list[EndpointDef]] = {}
    for ep in endpoints:
        if ep.service_hint not in by_service:
            by_service[ep.service_hint] = []
        by_service[ep.service_hint].append(ep)
    return by_service


def _format_endpoint_line(ep: EndpointDef) -> str:
    """Format single endpoint line."""
    methods_str = " ".join(ep.methods)
    return f"  {ep.path:<20} {methods_str:<6} {ep.service_hint} ({Path(ep.source_file).name})"


def _format_endpoints(endpoints: list[EndpointDef]) -> list[str]:
    """Generate ENDPOINTS section."""
    if not endpoints:
        return []
    
    lines = [f"ENDPOINTS[{len(endpoints)}]:"]
    by_service = _group_endpoints_by_service(endpoints)
    
    for service, eps in by_service.items():
        for ep in eps[:5]:  # Limit to 5 per service
            lines.append(_format_endpoint_line(ep))
        if len(eps) > 5:
            lines.append(f"  ... and {len(eps) - 5} more endpoints for {service}")
    lines.append("")
    return lines


def _format_cycles(cycles: list[list[str]]) -> list[str]:
    """Generate CYCLES section."""
    if not cycles:
        return []
    lines = [f"CYCLES[{len(cycles)}]:"]
    lines.extend(f"  {' → '.join(cycle)}" for cycle in cycles)
    lines.append("")
    return lines


def _format_hubs(hubs: list[str]) -> list[str]:
    """Generate HUBS section."""
    if not hubs:
        return []
    lines = [f"HUBS[{len(hubs)}]:"]
    lines.extend(f"  {hub}" for hub in hubs)
    lines.append("")
    return lines


def generate_toon(topology: InfraTopology, project_name: Optional[str] = None) -> str:
    """
    Generate toon format output for infrastructure status.
    
    Args:
        topology: InfraTopology object
        project_name: Optional project name (defaults to 'project')
        
    Returns:
        Toon-formatted string
    """
    project = project_name or "project"
    services = list(topology.services.values())
    endpoints = topology.endpoints
    anomalies = topology.detect_anomalies()
    
    lines = []
    lines.extend(_format_header(project, len(services)))
    lines.extend(_format_health(services, anomalies))
    lines.extend(_format_alerts(anomalies))
    lines.extend(_format_services(services))
    lines.extend(_format_endpoints(endpoints))
    lines.extend(_format_cycles(topology.detect_cycles()))
    lines.extend(_format_hubs(topology.find_hubs()))
    
    return "\n".join(lines)


def save_toon(topology: InfraTopology, output_path: Path, project_name: Optional[str] = None):
    """
    Save toon format to file.
    
    Args:
        topology: InfraTopology object
        output_path: Path to save the toon file
        project_name: Optional project name
    """
    toon_content = generate_toon(topology, project_name)
    output_path.write_text(toon_content)
